version: '3.8'

services:
  web:
    container_name: web_prod
    build: ./app
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  nginx:
    container_name: nginx_prod
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8080
    ports:
      - 8080:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
